plugins {
    alias(libs.plugins.android.library)
}

android {
    namespace 'no.nordicsemi.android.log'
    compileSdk = 37

    defaultConfig {
        minSdk = 16
    }

    buildTypes {
        release {
            minifyEnabled false
            consumerProguardFiles 'log-proguard-rules.pro'
        }
    }

    publishing {
        singleVariant('release') {
            withSourcesJar()
            withJavadocJar()
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    lint {
        targetSdk 37
    }
    testOptions {
        targetSdk 37
    }
}

dependencies {
    // Required for @NonNull and @Nullable
    api libs.androidx.annotation
}

// === Maven Central configuration ===
if (rootProject.file('gradle/publish-module.gradle').exists()) {
    ext {
        POM_ARTIFACT_ID = 'log'
        POM_NAME = 'Timber extension for nRF Logger Library'
        POM_PACKAGING = 'aar'
    }
    apply from: rootProject.file('gradle/publish-module.gradle')
}

afterEvaluate {
    generateMetadataFileForReleasePublication.dependsOn androidSourcesJar
}
