[versions]
android_gradle_plugin = "9.3.1"
nexus_publish_plugin  = "2.0.0"
androidx_fragment     = "1.8.9"
androidx_annotation   = "1.10.0"
material_design       = "1.14.0"
timber                = "5.0.1"

[plugins]
android_application   = { id = "com.android.application", version.ref = "android_gradle_plugin" }
android_library       = { id = "com.android.library", version.ref = "android_gradle_plugin" }
nexus_publish         = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus_publish_plugin" }

[libraries]
androidx_fragment     = { module = "androidx.fragment:fragment", version.ref = "androidx_fragment" }
androidx_annotation   = { module = "androidx.annotation:annotation", version.ref = "androidx_annotation" }
material_design       = { module = "com.google.android.material:material", version.ref = "material_design" }
timber                = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
