plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace "no.nordicsemi.android.log.example"
    compileSdk = 37

    defaultConfig {
        applicationId "no.nordicsemi.android.log.example"
        minSdk = 21
        targetSdk = 37
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.txt'
        }
    }
    compileOptions {
        targetCompatibility JavaVersion.VERSION_11
        sourceCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation project(':log')
    implementation libs.material.design
    implementation libs.androidx.fragment
}
