plugins {
    alias(libs.plugins.android.library)
}

android {
    namespace 'no.nordicsemi.android.log.timber'
    compileSdk = 37

    defaultConfig {
        minSdk = 16
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    publishing {
        singleVariant('release') {
            withSourcesJar()
            withJavadocJar()
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    lint {
        targetSdk 37
    }
    testOptions {
        targetSdk 37
    }
}

dependencies {
    api project(':log')
    api libs.timber
}

// === Maven Central configuration ===
if (rootProject.file('gradle/publish-module.gradle').exists()) {
    ext {
        POM_ARTIFACT_ID = 'log-timber'
        POM_NAME = 'nRF Logger API Library'
        POM_PACKAGING = 'aar'
    }
    apply from: rootProject.file('gradle/publish-module.gradle')
}

afterEvaluate {
    generateMetadataFileForReleasePublication.dependsOn androidSourcesJar
}